spring:
  application:
    name: authorization-server
#  security:
#    user:
#      name: artur
#      password: pass123
#      roles: ADMIN,USER


server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
  instance:
    hostname: localhost
    non-secure-port: 8761
    prefer-ip-address: true
#security:
#  oauth2:
#    client:
#      client-id: mobile
#      client-secret: pin
#      access-token-validity-seconds: 3600
#      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
#      scope: READ,WRITE
#    authorization:
#      check-token-access: permitAll
