spring:
  application:
    name: authorization-server
  datasource:
#    hikari:
#      connectionTimeout: 20000
#      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/testauth
    username: arturjakubowski
    password:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
  instance:
    hostname: localhost
    non-secure-port: 8761
    prefer-ip-address: true

logging:
  level:
    org:
      hibernate:
        type: trace
