FROM openjdk:11

ADD build/libs/post-service-0.0.1-SNAPSHOT.jar post-service-0.0.1-SNAPSHOT.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "post-service-0.0.1-SNAPSHOT.jar"]

MAINTAINER Artur Jakubowski
