version: "3"
services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - DB_SERVER=authdb
      - POSTGRES_DB=authdb
      - POSTGRES_USER=arturjakubowski
      - POSTGRES_PASSWORD=password
    ports:
      - 8081:8081
    links:
      - authdb

  post-service:
    build: ./post-service
    container_name: post-service
    environment:
      - DB_SERVER=postdb
      - POSTGRES_DB=postdb
      - POSTGRES_USER=arturjakubowski
      - POSTGRES_PASSWORD=password
    ports:
      - 8082:8082
    links:
      - postdb

  email-service:
    build: ./email-service
    container_name: email-service
    ports:
      - 8083:8083

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - 8888:8888

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - 8761:8761

  authdb:
    image: postgres:latest
    container_name: authdb
    volumes:
      - authdb:/var/lib/postgresql/data
    ports:
      - 5431:5431
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=arturjakubowski
      - POSTGRES_PASSWORD=password

  postdb:
    image: postgres:latest
    container_name: postdb
    volumes:
      - postdb:/var/lib/postgresql/data
    ports:
      - 5430:5430
    environment:
      - POSTGRES_DB=postdb
      - POSTGRES_USER=arturjakubowski
      - POSTGRES_PASSWORD=password

volumes:
  authdb:
  postdb:
