version: "3"

services:

  bloget-ui:
    build: ./bloget-ui
    container_name: bloget-ui
    ports:
      - 3000:3000

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    depends_on:
      - config-server
      - service-registry

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - 8081:8081
    depends_on:
      - authdb
      - config-server
      - service-registry
      - api-gateway
    links:
      - authdb

  post-service:
    build: ./post-service
    container_name: post-service
    environment:
      CONFIG_URI: http://config-server:8888
      EUREKA_URI: http://eureka-server:8761/eureka/
      DB_SERVER: postdb
      MONGO_DB: postdb
      MONGO_PORT: 27018
      MONGO_USER: root
      MONGO_PASS: password
    ports:
      - 8082:8082
    expose:
      - 8082
    depends_on:
      - postdb
      - config-server
      - service-registry
      - api-gateway
    links:
      - postdb

  email-service:
    build: ./email-service
    container_name: email-service
    ports:
      - 8083:8083
    depends_on:
      - config-server
      - service-registry
      - api-gateway

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - 8888:8888

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - 8761:8761
    depends_on:
      - config-server

  authdb:
    image: mongo:latest
    container_name: authdb
    restart: always
    volumes:
      - authdb:/data/db
    ports:
      - 27017:27017

  postdb:
    image: mongo:latest
    container_name: postdb
    restart: always
    volumes:
      - postdb:/data/db
    ports:
      - 27018:27017

volumes:
  authdb:
  postdb:
