version: "3"
services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    depends_on:
      - config-server

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - DB_SERVER=authdb
      - MONGO_DB=authdb
      - MONGO_PORT=5431
      - MONGO_USER=root
      - MONGO_PASS=pass
    ports:
      - 8081:8081
    depends_on:
      - authdb
      - config-server

  post-service:
    build: ./post-service
    container_name: post-service
    environment:
      - DB_SERVER=postdb
      - MONGO_DB=postdb
      - MONGO_PORT=5430
      - MONGO_USER=root
      - MONGO_PASS=pass
    ports:
      - 8082:8082
    depends_on:
      - postdb
      - config-server

  email-service:
    build: ./email-service
    container_name: email-service
    ports:
      - 8083:8083
    depends_on:
      - config-server

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - 8888:8888

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - 8761:8761
    depends_on:
      - config-server

  authdb:
    image: mongo-express
    container_name: authdb
    volumes:
      - authdb:/data/db
    ports:
      - 5431:5431
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass

  postdb:
    image: mongo-express
    container_name: postdb
    volumes:
      - postdb:/data/db
    ports:
      - 5430:5430
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass

volumes:
  authdb:
  postdb:
