server:
  port: 8080

spring:
  application:
    name: api-gateway

zuul:
  routes:
    service-registry:
      path: /eureka/**
      url: http://service-registry:8761/eureka/
    auth-service:
      path: /auth/**
      url: http://auth-service:8081
    post-service:
      path: /posts/**
      url: http://post-service:8082
    email-service:
      path: /emails/**
      url: http://email-service:8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  security:
    enabled: false
