server:
  port: 8083

spring:
  application:
    name: email-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    egister-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-registry:8761}
