server:
  port: 8082

spring:
  application:
    name: post-service
  data:
    mongodb:
      host: postdb
      port: 27017
      dbname: postdb
      username: root
      password: password

security:
  oauth2:
    resource:
      token-info-uri: http://auth-service:8081/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-registry:8761}
  instance:
    prefer-ip-address: true
