server:
  port: 8082

spring:
  application:
    name: post-service
  data:
    mongodb:
      host: postdb
      port: 27017
      database: postdb

security:
  oauth2:
    resource:
      token-info-uri: http://auth-service:8081/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true
