server:
  port: 8082

spring:
  application:
    name: post-service
  data:
    mongodb:
      host: ${DB_SERVER}
      port: ${MONGO_PORT}
      dbname: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASS}

security:
  oauth2:
    resource:
      token-info-uri: http://auth-service:8081/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
