server:
  port: 8082

spring:
  application:
    name: post-service
  data:
    mongodb:
      host: postdb
      port: 27017
      database: postdb


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

secret-key: p4m3NZ12ZWE6S5652vLEig7rOYqLnf7c
expiration-time: 7200

security:
  basic:
    enable: false
