version: "3"
services:

  api-gateway:
    build: ./api/v1/api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080

  auth-service:
    build: ./api/v1/auth-service
    container_name: auth-service
    environment:
      - DB_SERVER=auth-database
      - POSTGRES_DB=adb
      - POSTGRES_USER=arturjakubowski
      - POSTGRES_PASSWORD=password
    ports:
      - 8081:8081
    links:
      - postgres

  post-service:
    build: ./api/v1/post-service
    container_name: post-service
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=postdb
      - POSTGRES_USER=arturjakubowski
      - POSTGRES_PASSWORD=password
    ports:
      - 8082:8082
    links:
      - postgres

  email-service:
    build: ./api/v1/email-service
    container_name: email-service
    ports:
      - 8083:8083

  log-service:
    build: ./api/v1/log-service
    container_name: log-service
    ports:
      - 8083:8083

  service-registry:
    build: ./api/v1/service-registry
    container_name: service-registry
    ports:
      - 8083:8083

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5431:5431
    environment:
      - POSTGRES_AUTH_DB=authdb
      - POSTGRES_POST_DB=postdb
      - POSTGRES_USER=arturjakubowski
      - POSTGRES_PASSWORD=password

volumes:
  postgres:
